baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

[author]
  name = "Vinicius Saab"
  
[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Code and More"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]
  
  homeSubtitle = "Software Craftsman, Agile, Cook, Professional Amateur."
  
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  
  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/eosapolacaraio"

  [[params.social]]
    name = "email"
    url  = "mailto:viniciusmsaab@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/vinisaab"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/vinicius-saab-77866938/"

[languages]
  [languages.en]
    title = "Vinicius Saab"
    subtitle = "Code and More"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ /Code"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
		identifier = "blog"
		name       = "Blog"
		url        = "/posts"


# And you can even create generic menu
#[menu]
#  [[menu.main]]
#    identifier = "about"
#   name       = "Gui"
#    url        = "/about"
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"